### ISSUE TITLE
Firefox Fix

### ISSUE THREAD

**Issue by Gaz492** [modmuss50/YarnDiff#1]
Need to allow an OPTIONS request that has the following headers on https://meta.fabricmc.net/v2/versions/yarn

Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET

**Comment by JamiesWhiteShirt** [comment]
[According to MDN, the cross-origin requests to meta.fabricmc.net do not qualify as "Simple requests"](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests) because of the following condition:

> No event listeners are registered on any XMLHttpRequestUpload object used in the request; these are accessed using the XMLHttpRequest.upload property.

axios-progress-bar installs an such an event listener. All the other conditions appear to be fulfilled.

In my environment, Firefox (69.0.2) interprets it as a request that requires a CORS preflight, but both Chrome (76.0.3809.100) and Edge (42.17134.1.0) appear not to (breaking the spec).

Fabric-Meta should still have Access-Control headers as described in the issue, but until that is fixed, I expect it to be possible to work around the issue by disabling the progress bar.

**Comment by modmuss50** [comment]
your fix didnt help, and adding into nginx didnt fix the issue.

```
add_header 'Access-Control-Allow-Origin' '*';
add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS, HEAD";
```


 `curl -I https://meta.fabricmc.net/v2/versions/yarn/123132?` (Change the number to ensure its not being chached) reports the correct headers.

**Comment by modmuss50** [comment]
Fixed, by letting javalin do it all.
